### ISSUE TITLE
Lua Setup

### ISSUE THREAD

**Issue by Dope25** [thijsvanloef/barotrauma-server-docker#3]
**Is your feature request related to a problem? Please describe.**
Due to steamcmd using the validate flag, it is impossible to install serverside Lua.

**Describe the solution you'd like**
Add an enviromental boolean for installing Lua after steamcmd finishes but before the game launches:
wget https://github.com/evilfactory/LuaCsForBarotrauma/releases/download/latest/luacsforbarotrauma_patch_linux_server.zip
unzip that into game folder and overwrite

**Describe alternatives you've considered**
Disabling validate 

**Additional context**
[Manual Lua install guide](https://evilfactory.github.io/LuaCsForBarotrauma/lua-docs/manual/installing-lua-for-barotrauma-manually/)
[Lua Releases](https://github.com/evilfactory/LuaCsForBarotrauma/releases/tag/latest)

**Comment by thijsvanloef** [comment]
Released 0.5.0 with the added INSTALL_LUA environment variable :)
