### ISSUE TITLE
Additional Symlinks

### ISSUE THREAD

**Issue by Dope25** [thijsvanloef/barotrauma-server-docker#4]
**Is your feature request related to a problem? Please describe.**
It would make it much easier if more links were visible in the /barotrauma bind mount:
WorkshopMods/Installed
config_player.xml

**Describe the solution you'd like**
Add config_player.xml and WorkshopMods/Installed to the /barotrauma bind mount
**Describe alternatives you've considered**
Bind mounting /game/barotrauma myself and then navigating to the files/directories.

**Additional context**
N/A

**Comment by thijsvanloef** [comment]
Hi @Dope25 Sorry for the delay, I'm starting work on the config_player.xml mounting

**Comment by thijsvanloef** [comment]
I was not able to add the WorkshopMods/Installed mountpoint. However I think I've found a workaround with the LocalMods folder, I've released 0.4.0 that has both the symlink added.
